version: '3.8'
services:
    web:
        build: .
        restart: always
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code 
        ports:
            - '8000:8000'
        depends_on:
            - redis
        env_file: .env

    redis:
        image: 'redis'

    celery:
        build: .
        container_name: 'appbank_celery_worker'
        command: celery -A appbank worker -l info
        volumes:
        - .:/code
        depends_on:
        - redis
        - web
        links:
        - redis
        env_file: .env
    
    celery-beat:
        build: .
        container_name: 'appbank_celery_beat'
        command: celery -A appbank beat -l info
        volumes:
        - .:/code
        depends_on:
        - redis
        - web
        links:
        - redis
        env_file: .env
    
    db:
        image: postgres:14.0-alpine

        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=bank_user
        - POSTGRES_PASSWORD=bank_pass
        - POSTGRES_DB=bank_db

volumes:
  postgres_data:
