version: '3.8'
services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code 
        ports:
            - '0.0.0.0:8000:8000'

    celery:
        build: .
        command: celery -A appbank worker -l info
        volumes:
        - .:/code
        depends_on:
        - db
        - redis

    celery-beat:
        build: .
        command: celery -A appbank beat -l info
        volumes:
        - .:/code
        depends_on:
        - db
        - redis