# Generated by Django 3.1.14 on 2022-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
